[project]
name = "cbr-lab-local"
version = "0.1.0"
description = "Hands-on CBR + local LLM (Ollama) teaching project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.black]
line-length = 100
